# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fahim/Projects/CPP/MatrixMulti

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fahim/Projects/CPP/MatrixMulti

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fahim/Projects/CPP/MatrixMulti/CMakeFiles /home/fahim/Projects/CPP/MatrixMulti/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fahim/Projects/CPP/MatrixMulti/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MatrixMulti

# Build rule for target.
MatrixMulti: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MatrixMulti
.PHONY : MatrixMulti

# fast build rule for target.
MatrixMulti/fast:
	$(MAKE) -f CMakeFiles/MatrixMulti.dir/build.make CMakeFiles/MatrixMulti.dir/build
.PHONY : MatrixMulti/fast

CMatrix.o: CMatrix.cpp.o

.PHONY : CMatrix.o

# target to build an object file
CMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/MatrixMulti.dir/build.make CMakeFiles/MatrixMulti.dir/CMatrix.cpp.o
.PHONY : CMatrix.cpp.o

CMatrix.i: CMatrix.cpp.i

.PHONY : CMatrix.i

# target to preprocess a source file
CMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/MatrixMulti.dir/build.make CMakeFiles/MatrixMulti.dir/CMatrix.cpp.i
.PHONY : CMatrix.cpp.i

CMatrix.s: CMatrix.cpp.s

.PHONY : CMatrix.s

# target to generate assembly for a file
CMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/MatrixMulti.dir/build.make CMakeFiles/MatrixMulti.dir/CMatrix.cpp.s
.PHONY : CMatrix.cpp.s

MatrixMultiplication2.o: MatrixMultiplication2.cpp.o

.PHONY : MatrixMultiplication2.o

# target to build an object file
MatrixMultiplication2.cpp.o:
	$(MAKE) -f CMakeFiles/MatrixMulti.dir/build.make CMakeFiles/MatrixMulti.dir/MatrixMultiplication2.cpp.o
.PHONY : MatrixMultiplication2.cpp.o

MatrixMultiplication2.i: MatrixMultiplication2.cpp.i

.PHONY : MatrixMultiplication2.i

# target to preprocess a source file
MatrixMultiplication2.cpp.i:
	$(MAKE) -f CMakeFiles/MatrixMulti.dir/build.make CMakeFiles/MatrixMulti.dir/MatrixMultiplication2.cpp.i
.PHONY : MatrixMultiplication2.cpp.i

MatrixMultiplication2.s: MatrixMultiplication2.cpp.s

.PHONY : MatrixMultiplication2.s

# target to generate assembly for a file
MatrixMultiplication2.cpp.s:
	$(MAKE) -f CMakeFiles/MatrixMulti.dir/build.make CMakeFiles/MatrixMulti.dir/MatrixMultiplication2.cpp.s
.PHONY : MatrixMultiplication2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MatrixMulti"
	@echo "... CMatrix.o"
	@echo "... CMatrix.i"
	@echo "... CMatrix.s"
	@echo "... MatrixMultiplication2.o"
	@echo "... MatrixMultiplication2.i"
	@echo "... MatrixMultiplication2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

